---
- name: Configure Nginx Web server
  hosts: linux
  gather_facts: false

  vars_prompt:
    - name: user
      prompt: "Enter ssh user"
      private: false
    - name: password
      prompt: "Enter password"
      private: false

  vars:
    ansible_user: "{{ user }}"
    ansible_password: "{{ password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Install nginx
      package:
        name:
          - nginx
        state: latest
      become: true

    - name: Copy index.html
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: "0644"
      become: true

    - name: Start nginx service
      service:
        name: nginx
        state: started
      become: true
